stages:
  - mirror
  - build
  - docstats

variables:
  ANDROID_HOME: "/opt/android-sdk"
  ANDROIDKEY_ALIAS: "$ANDROIDKEY_ALIAS"
  ANDROIDKEY_PASS: "$ANDROIDKEY_PASS"
  ANDROIDKEY_LOCATION: "$ANDROIDKEY_LOCATION"

mirror_repo:
  stage: mirror
  only:
    - master
    - develop
  script:
    - git checkout master
    - git pull origin master
    - git push git@github.com:namboy94/hikvision-client.git master --force
    - git checkout develop
    - git pull origin develop
    - git push git@github.com:namboy94/hikvision-client.git develop --force

#build_release:
# stage: build
#  only:
#    - master
#    - test_build
#  script:
#    - cp $GOOGLESERVICES_JSON hikvision-client-android/google-services.json
#    - python signed_apk_enabler.py
#    - gradle build
#    - python noanalytics.py stash
#    - ./gradlew assembleRelease
#    - python noanalytics.py restore
#    - python github-release.py $GITHUBAUTH

#  artifacts:
#      paths:
#        - hikvision-client-java/build/libs
#        - hikvision-client-lib/build/libs
#        - hikvision-client-android/build/outputs/apk

#generate_git_stats:
#  stage: docstats
#  only:
#    - master
#    - develop
#  script:
#    - gitstats . git_stats
#    - rsync -av git_stats/ www.krumreyh.com@ssh.strato.de:~/programming_pages/hikvision-client/git_stats --delete-after

